sci/Models/Mem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mem()
        {
            this.Pag = new HashSet<Pag>();
        }
    
        public int Cod { get; set; }
        public string Sesso { get; set; }
        public string Nom { get; set; }
        public string Titolo { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Ist { get; set; }
        public string Via { get; set; }
        public string CAP { get; set; }
        public string Cit { get; set; }
        public string Naz { get; set; }
        public Nullable<System.DateTime> DaNa { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<short> DimAn { get; set; }
        public Nullable<bool> NoStampa { get; set; }
        public Nullable<System.DateTime> Modificato { get; set; }
        public Nullable<int> PresentatoDa { get; set; }
        public Nullable<bool> FlagRegalo { get; set; }
        public Nullable<int> PresentatoDa2 { get; set; }
        public Nullable<bool> FlagRegalo2 { get; set; }
        public Nullable<short> AnnoPresentazione { get; set; }
        public string CodTitStu { get; set; }
    
        public virtual TabNaz TabNaz { get; set; }
        public virtual TabSex TabSex { get; set; }
        public virtual TabTitStu TabTitStu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pag> Pag { get; set; }
    }
}

sci/Controllers/MemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sci.Models;
using PagedList;
using System.Collections;

namespace sci.Controllers
{
    public class MemsController : Controller
    {
        private sci_newEntities db = new sci_newEntities();

       
            // GET: Mems
            public ActionResult Index(string sortOrder, string currentFilter, string searchString,int? page)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Cod" ? "cod_desc" : "Cod";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var mems = from m in db.Mem select m;
            var data = db.Mem.Select(m => m).ToList().OrderBy(m => m.Cognome);
            ViewBag.data = data; 

            if (!String.IsNullOrEmpty(searchString))
            {
                if (searchString.All(char.IsDigit))
                {
                    mems = mems.Where(m => m.Cognome.StartsWith(searchString)); 
                 }
                
            }
                     
            switch (sortOrder)
            {
                case "name_desc":
                    mems = mems.OrderByDescending(m => m.Cognome);
                    break;
                case "Cod":
                    mems = mems.OrderBy(m => m.Cod);
                    break;
                
                default:  // Name ascending 
                    mems = mems.OrderBy(m => m.Cognome);
                    break;
            }

            int pageSize = 50;
            int pageNumber = (page ?? 1);

            return View(mems.ToPagedList(pageNumber, pageSize));
        }



        [HttpPost]
        public ActionResult Index(string searchString)
        {
            ViewBag.CurrentFilter = searchString;

            var mems = db.Mem.Where(m => m.Cognome.StartsWith(searchString) || m.Cod.ToString().StartsWith(searchString)); 

            return View(mems);
        }

        // GET: Mems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Mem mem = db.Mem.Find(id);
            var query = db.Pag.Max(x => x.AnnoP);

            if (mem == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Edit", "Pags", new { codp = id, annop = query });
        }

        // GET: Mems/Create
        public ActionResult Create()
        {
            ViewBag.Naz = new SelectList(db.TabNaz, "CodNaz", "DescrNaz");
            ViewBag.Sesso = new SelectList(db.TabSex, "CodSex", "DescrSex");
            ViewBag.CodTitStu = new SelectList(db.TabTitStu, "TCodTitStu", "DescrTitStu");
            return View();
        }

        // POST: Mems/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Cod,Sesso,Nom,Titolo,Nome,Cognome,Ist,Via,CAP,Cit,Naz,DaNa,Tel,Fax,Email,DimAn,NoStampa,Modificato,PresentatoDa,FlagRegalo,PresentatoDa2,FlagRegalo2,AnnoPresentazione,CodTitStu")] Mem mem)
        {
            if (ModelState.IsValid)
            {
                db.Mem.Add(mem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Naz = new SelectList(db.TabNaz, "CodNaz", "DescrNaz", mem.Naz);
            ViewBag.Sesso = new SelectList(db.TabSex, "CodSex", "DescrSex", mem.Sesso);
            ViewBag.CodTitStu = new SelectList(db.TabTitStu, "TCodTitStu", "DescrTitStu", mem.CodTitStu);
            return View(mem);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sci/Views/Mems/Create.cshtml
@model sci.Models.Mem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Sesso, "Sesso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sesso", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sesso, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titolo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titolo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titolo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cognome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Via, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Via, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Via, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CAP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CAP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CAP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naz, "Naz", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Naz", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Naz, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaNa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaNa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DaNa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DimAn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DimAn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DimAn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoStampa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NoStampa)
                    @Html.ValidationMessageFor(model => model.NoStampa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modificato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modificato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modificato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PresentatoDa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PresentatoDa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PresentatoDa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlagRegalo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FlagRegalo)
                    @Html.ValidationMessageFor(model => model.FlagRegalo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PresentatoDa2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PresentatoDa2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PresentatoDa2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlagRegalo2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FlagRegalo2)
                    @Html.ValidationMessageFor(model => model.FlagRegalo2, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnnoPresentazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnnoPresentazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnnoPresentazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodTitStu, "CodTitStu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodTitStu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodTitStu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sci/Views/Mems/Delete.cshtml
@model sci.Models.Mem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Sei sicuro di voler eliminare il socio @Html.DisplayFor(model => model.Cognome) @Html.DisplayFor(model => model.Nome) ?</h3>
<div>
    <h4>Mem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titolo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cognome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cognome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Via)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Via)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CAP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaNa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaNa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DimAn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DimAn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoStampa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoStampa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modificato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modificato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PresentatoDa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PresentatoDa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlagRegalo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlagRegalo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PresentatoDa2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PresentatoDa2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlagRegalo2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlagRegalo2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnnoPresentazione)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnnoPresentazione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TabNaz.DescrNaz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TabNaz.DescrNaz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TabSex.DescrSex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TabSex.DescrSex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TabTitStu.DescrTitStu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TabTitStu.DescrTitStu)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

sci/Views/Mems/Index.cshtml
@model PagedList.IPagedList<sci.Models.Mem>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";

}

<h2>Soci</h2>
<style>
    #button {
        margin-top: 3px;
        
        box-shadow: rgb(12, 54, 97) 0px 1px 0px 0px inset;
        background: linear-gradient(rgb(18, 77, 119) 5%, rgb(18, 77, 119) 100%) rgb(18, 77, 119);
        border-radius: 3px;
        border: 1px solid rgb(18, 77, 119);
        display: inline-block;
        cursor: pointer;
        color: rgb(255, 255, 255);
        font-family: "Trebuchet MS";
        font-size: 13px;
        padding: 6px 24px;
        text-decoration: none;
        text-shadow: rgb(21, 70, 130) 0px 1px 0px;
    }
</style>

<table class="table">
    <tr>
        <td colspan="3">
            @using (Html.BeginForm("Index", "Mems"))
            {

              

                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new
           {
               @id = "flexdatalist",
               name = "language22",
               list = "data",
               //data = ANDREBBE SOSTITUITO A LIST, INSERENDO LA LISTA DI TUTTI I NOMI
               multiple = "",
               SelectList = "1",
               MinLengthAttributeAdapter = "1",            
               onchange = "myFunction()",
               

           })
               
                <datalist id="data" >
 
                @foreach (var item in ViewBag.data)
                {
                    if (item.Cognome != null && item.Nome != null && item.Cognome.Length > 2)
                    {
                              <option style="background-color: red;color: red;">
                                  @item.Cognome
                                  @item.Nome                                 
                                  @item.Cod                               
                              </option>
                              }
                      }

                </datalist>
            }
        </td>

            <td>
                @using (Html.BeginForm("Create", "Mems", FormMethod.Get))
            {
                    <input type="submit" id="button" value="Nuovo Socio" />
                    
                }
            </td>
            </tr>

            <tr>
                <th>
                    @Html.ActionLink("Cognome", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    Nome
                </th>
                <th>
                    @Html.ActionLink("Codice", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                if (item.Cognome != null && item.Nome != null && item.Cognome.Length > 2)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cognome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            
                            @Html.DisplayFor(modelItem => item.Cod)
                           
                        </td>
                        <td>
                            @Html.ActionLink("Dettagli Socio", "Details", new { id = item.Cod })
                        </td>
                    </tr>
                }


            }

        </table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

@section Scripts {

 

    @Scripts.Render("~/bundles/jqueryval")
    
<link href="~/Scripts/jquery.flexdatalist.min.css" rel="stylesheet" type="text/css"/>
<script src="~/Scripts/jquery.flexdatalist.min.js"></script>

<script>

    $('#flexdatalist').flexdatalist({
        selectionRequired: true,
        minLength: 1,
        maxShownResults: 10,
    });
</script>

<script>
    function myFunction() {

        var codice = $('#codp').val();                       
        var annop = 2017;
        windows: location = "../Pags/Edit?codp=" + codice + "&annop=" + annop;
        
    }
</script>       
    
}